theme: jekyll-theme-cayman
title: Jay Authement's ePortfolio
description: Welcome to my ePortfolio page! Below contains some of my projects completed at SNHU, feel free to browse around!
logo: /assets/images/CircleLogo.png
title-img: /assets/images/CircleLogo.png
