theme: jekyll-theme-midnight
title: Jay Authement's ePortfolio
description: Welcome to my ePortfolio page! This page contains a few of my projects completed at Southern New Hampshire University.This page is desgined to showcase my skills in software design/ engineering, algorithm design/ data structures, and database design. Feel free to browse around and take a look at the included projects!
