theme: jekyll-theme-minimal
title: Jay Authement's ePortfolio
description: Welcome to my ePortfolio page! Below contains some of my projects completed at SNHU, feel free to browse around!
logo: /assets/images/Logo.png
