theme: jekyll-theme-midnight
title: Jay Authement's ePortfolio
description: Welcome to my ePortfolio page! This page contains a few of my projects completed at Southern New Hampshire University. Each project was created and later enhanced to show my proficiency in three major categories in the software development field, software design/engineering, algorithm design/structures, and database design. Feel free to browse around and take a look at my included projects!
