theme: jekyll-theme-midnight
title: Welcome to Jay Authement's ePortfolio!
description: Feel free to bookmark this site to keep an eye for future updates!
use_logo: true
logo: "/images/Logo.png?raw=true"
