theme: jekyll-theme-midnight
title-img: /images/Logo.png
title: Welcome to Jay Authement's ePortfolio!
description: Feel free to bookmark this site to keep an eye for future updates!
logo: ![image](/images/Logo.png)
