theme: jekyll-theme-midnight
title: Welcome to Jay Authement's ePortfolio!
description: Feel free to bookmark this site to keep an eye for future updates!
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

title-img: "assets/img/Logo.png"
