theme: jekyll-theme-midnight
#title: Jay Authement's ePortfolio
description: Welcome to my ePortfolio page! Below contains some of my projects completed at SNHU, feel free to browse around!
title: ![Jay Authement Logo](/assets/images/Logo.png)
